[package]
name = "ratatui-base16"
version = "0.3.1"
edition = "2021"
authors = ["Dheepak Krishnamurthy"]
description = "A base16 palette for ratatui"
license = "MIT"
repository = "https://github.com/kdheepak/ratatui-base16"
documentation = "https://docs.rs/ratatui-base16"


[dependencies]
figment = { version = "0.10.18", features = ["env", "toml", "yaml"] }
ratatui = { version = "0.26.2", features = ["serde"] }
serde = "1.0.201"
serde_with = "3.8.1"
thiserror = "1.0.60"
